language: python
# This version of python is only used to run tox.
python: 3.6

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

notifications:
  email: false

install:
  - pip install coveralls tox

matrix:
  allow_failures:
    - env: TOX_SKIP_ENV=".*django[^m].*"

script:
  - tox

after_success:
  - coveralls
